// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'providers/auth_provider.dart' as app_auth_provider;
import 'screens/home/home_screen.dart';
import 'screens/cart/cart_screen.dart';
import 'screens/profile/profile_screen.dart';
import 'screens/orders/order_status_screen.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU9O21EUgRick_YVVVQtmLsho-_e_pNRs',
    appId: '1:235791369176:web:4c812e1bcf7708080fe8ad',
    messagingSenderId: '235791369176',
    projectId: 'foodi-c7522',
    authDomain: 'foodi-c7522.firebaseapp.com',
    storageBucket: 'foodi-c7522.firebasestorage.app',
    measurementId: 'G-L6FDR2T0X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoT5YheoIU1l4YK5ORezm5deNd0rjWqDs',
    appId: '1:235791369176:android:0860accbe987c0db0fe8ad',
    messagingSenderId: '235791369176',
    projectId: 'foodi-c7522',
    storageBucket: 'foodi-c7522.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqJL-uSufaVJ0scguIjcZAfYOWrOqc_Dc',
    appId: '1:235791369176:ios:630a5823cd4bf8d80fe8ad',
    messagingSenderId: '235791369176',
    projectId: 'foodi-c7522',
    storageBucket: 'foodi-c7522.firebasestorage.app',
    iosBundleId: 'com.example.fooda',
  );
}
